security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
             id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:      ^/
            anonymous:    ~
            form_login:
                default_target_path: /profile
                username_parameter: login_form[username]
                password_parameter: login_form[password]
                provider:   fos_userbundle
                login_path: /profile/login
                check_path: /profile/login_check
            logout:
                path:       /profile/logout
                target:     /profile/login
                invalidate_session: false
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~
                remember_me_parameter: login_form[remember_me]

    access_control:
        - { path: ^/profile/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: ROLE_USER}
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
